name: Publish to Maven Repositories

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'The tag_version, e.g. x.x.x'
        default: 'x.x.x'
        required: true
        type: 'string'
      dry_run:
        description: 'Whether this is a dry_run publish.'
        default: false
        required: true
        type: 'boolean'

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_version }}
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Build with Maven
        run: mvn package

      - name: Publish to GitHub
        run: mvn -e deploy -P github,default
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish Javadocs to GitHub
        run: mvn site -P github,default
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '11'
          server-id: central
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Publish to Apache Maven Central
        run: mvn deploy -P release,default
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}